#!/usr/bin/env python3
"""
Database Migration Script for encryption_salt Column Fix

This script addresses the production database schema mismatch where the
encryption_salt column is missing from the users table in the production
Cloud SQL instance but exists in the local development SQLite database.

Usage:
    python scripts/fix_encryption_salt_migration.py [environment]

    environments: local, production

Author: Database Migration Diagnostic
Date: 2025-11-18
"""

import os
import sys
import argparse
from sqlalchemy import text
from backend.app import create_app, db


def fix_local_development():
    """Fix the local SQLite database schema."""
    print("🔧 Fixing local development database...")

    app = create_app()
    with app.app_context():
        try:
            # Check if encryption_salt column exists
            result = db.session.execute(
                text(
                    """
                SELECT name FROM pragma_table_info('users') 
                WHERE name = 'encryption_salt'
            """
                )
            ).fetchone()

            if result:
                print("✅ encryption_salt column already exists in local database")
                return True

            # Add the missing column
            db.session.execute(
                text(
                    """
                ALTER TABLE users ADD COLUMN encryption_salt VARCHAR(64)
            """
                )
            )
            db.session.commit()

            print("✅ Successfully added encryption_salt column to local database")
            return True

        except Exception as e:
            print(f"❌ Error fixing local database: {e}")
            return False


def fix_production_database():
    """Generate the production migration SQL script."""
    print("🔧 Generating production database migration script...")

    migration_sql = """
-- Production Database Migration: Add encryption_salt Column
-- Generated by Database Migration Diagnostic Tool
-- Date: 2025-11-18

-- WARNING: This migration adds the missing encryption_salt column to the users table
-- in the production Cloud SQL database. This is required to fix the schema mismatch
-- where the application code expects this column but it doesn't exist in production.

-- Step 1: Add the encryption_salt column
ALTER TABLE users ADD COLUMN IF NOT EXISTS encryption_salt VARCHAR(64);

-- Step 2: Verify the column was added
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'users' AND column_name = 'encryption_salt';

-- Step 3: Update any existing users to have NULL encryption_salt (this is expected)
-- The column is nullable so existing users will have NULL values until they register

-- Rollback (if needed):
-- ALTER TABLE users DROP COLUMN IF EXISTS encryption_salt;

-- Migration completed successfully!
"""

    # Write migration script to file
    script_path = "/Users/matthewalviar/Documents/School/OSU Online CS/2025/Fall 2025/CS467/Secure-Password-Manager/scripts/production_migration.sql"
    with open(script_path, "w") as f:
        f.write(migration_sql)

    print(f"✅ Production migration script generated: {script_path}")

    # Also provide direct SQL commands for manual execution
    print("\n" + "=" * 60)
    print("🚀 MANUAL EXECUTION REQUIRED FOR PRODUCTION")
    print("=" * 60)
    print("\nTo apply this fix to production, run these commands:")
    print("\n1. Connect to your Cloud SQL instance:")
    print("   gcloud sql connect [INSTANCE_NAME] --user=postgres")
    print("\n2. Connect to your database:")
    print("   \\c [DATABASE_NAME]")
    print("\n3. Execute the migration:")
    migration_commands = """
   -- Add the missing column
   ALTER TABLE users ADD COLUMN IF NOT EXISTS encryption_salt VARCHAR(64);
   
   -- Verify the column was added
   \\d users
   """
    print(migration_commands)
    print("\n4. Test the fix:")
    print(
        "   SELECT column_name FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'encryption_salt';"
    )

    return True


def verify_fix(environment="local"):
    """Verify that the encryption_salt column exists."""
    print(f"🔍 Verifying fix for {environment} environment...")

    app = create_app()
    with app.app_context():
        try:
            if environment == "local":
                # SQLite specific check
                result = db.session.execute(
                    text(
                        """
                    SELECT name FROM pragma_table_info('users') 
                    WHERE name = 'encryption_salt'
                """
                    )
                ).fetchone()

            else:
                # PostgreSQL specific check
                result = db.session.execute(
                    text(
                        """
                    SELECT column_name FROM information_schema.columns 
                    WHERE table_name = 'users' AND column_name = 'encryption_salt'
                """
                    )
                ).fetchone()

            if result:
                print(f"✅ {environment} database: encryption_salt column verified")
                return True
            else:
                print(f"❌ {environment} database: encryption_salt column NOT found")
                return False

        except Exception as e:
            print(f"❌ Error verifying {environment} database: {e}")
            return False


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(description="Fix encryption_salt column migration")
    parser.add_argument(
        "environment", choices=["local", "production"], help="Target environment to fix"
    )
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="Only verify the fix, do not apply it",
    )

    args = parser.parse_args()

    print("🔧 Database Schema Migration Diagnostic - Encryption Salt Fix")
    print("=" * 65)

    if args.verify_only:
        return verify_fix(args.environment)

    if args.environment == "local":
        success = fix_local_development()
    elif args.environment == "production":
        success = fix_production_database()

    if success:
        print("\n✅ Migration script completed successfully!")

        # Offer to verify
        verify_choice = input("\nWould you like to verify the fix? (y/n): ").lower()
        if verify_choice == "y":
            verify_fix(args.environment)
    else:
        print("\n❌ Migration script failed!")
        sys.exit(1)


if __name__ == "__main__":
    main()
